name: binance_chain
description: Binance Chain Dart SDK
version: 0.0.5
homepage: https://github.com/Tbcc-wallet/binance_chain_dart
repositoy: https://github.com/Tbcc-wallet/binance_chain_dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.12.1
  protoc_plugin: ^19.0.1
  protobuf: ^1.0.1
  bip39: ^1.0.3
  pointycastle: ^1.0.2
  web_socket_channel: ^1.1.0
  decimal: ^0.3.5
  hex: ^0.1.2
  bs58check: ^1.0.1
  convert: ^2.1.1
  fixnum: ^0.10.11
  meta: ^1.2.3
  

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
