name: binance_chain
description: Binance Chain Dart SDK. Get Binance DEX info, send tokens, place orders, keep account balance using HTTP or WebSocket! 
version: 1.0.0
homepage: https://github.com/Tbcc-wallet/binance_chain_dart
repositoy: https://github.com/Tbcc-wallet/binance_chain_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  protoc_plugin: ^20.0.0
  protobuf: ^2.0.0
  bip39: ^1.0.6
  pointycastle: ^3.1.1
  web_socket_channel: ^2.1.0
  decimal: ^1.2.0
  hex: ^0.2.0
  bs58check: ^1.0.2
  convert: ^3.0.0
  fixnum: ^1.0.0
  uuid: ^3.0.4
  

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.7
